### ISSUE TITLE
how to build for mac

### ISSUE THREAD

**Issue by OneMoreThing** [shubapp/u2bear#20]
how to build for mac, please

**Comment by deanshub** [comment]
sorry, i haven't tried it on mac...
could you try and run gulp and paste the error?

**Comment by lorefnon** [comment]
gulp fails with the following error: 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

This is because the run task has hardcoded paths with windows path separators:

```
gulp.task('run', function () {
	cp.spawn("f:\\git\\node-webkit-v0.10.5-win-ia32\\nw.exe",["f:\\git\\u2bear\\."]);
});
```

However when I run `nodewebkit .` in the project directory, the application does start up but I see the following error in console: 

```
[19277:0111/234459:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[19278:0111/234459:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
```
Although the listing of top videos is visible, attempting to play the videos fail with the following errors in console: 

```
[20742:0111/235034:INFO:CONSOLE(2)] ""Error: [$rootScope:inprog] http://errors.angularjs.org/1.2.26/$rootScope/inprog?p0=%24digest\n    at Error (native)\n    at file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js:1:450\n    at f (file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js:2:18070)\n    at l.$apply (file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js:2:21866)\n    at l.e.mouseMovement (file:///Users/lorefnon/workspace/u2bear/js/controllers.js:1:2812)\n    at Object.fn (file:///Users/lorefnon/workspace/u2bear/js/controllers.js:1:2897)\n    at l.$digest (file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js:2:20453)\n    at l.$apply (file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js:2:21935)\n    at HTMLElement.\u003Canonymous\u003E (file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js:3:31620)\n    at HTMLElement.it.event.dispatch (file:///Users/lorefnon/workspace/u2bear/js/lib/jquery-1.11.1.min.js:2:17661)"", source: file:///Users/lorefnon/workspace/u2bear/js/lib/angular.min.js (2)
[20742:0111/235034:INFO:CONSOLE(1)] ""VIDEOJS:" "ERROR:" "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" "The video could not be loaded, either because the server or network failed or because the format is not supported." {"code":4,"message":"The video could not be loaded, either because the server or network failed or because the format is not supported."}", source: file:///Users/lorefnon/workspace/u2bear/js/lib/video.js (1)
```

Also the text bar with placeholder "Search phrase

**Comment by lorefnon** [comment]
Let me know if some other information would be helpful for debugging. I installed node-webkit through the [npm package](https://www.npmjs.com/package/nodewebkit). I had to install it globally since this is not a project dependency. 

I am running Mac OS X Yeosemite.
